services:
  online_shop:
    build:
      context: .
    container_name: online_shop
    ports:
      - "5173:5173"
    networks:
      - my-net
    depends_on:
      - nginx
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://13.202.205.13:5173"]
      interval: 30s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - my-net

networks:
  my-net:

